# Generated by Django 6.0 on 2026-02-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
        ('vocab', '0002_word_example_word_example_translation_word_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='custom_list',
        ),
        migrations.AddField(
            model_name='user',
            name='active_lists',
            field=models.ManyToManyField(blank=True, related_name='active_of', to='vocab.vocabularylist'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_lists',
            field=models.ManyToManyField(blank=True, related_name='custom_of', to='vocab.vocabularylist'),
        ),
    ]
