# Generated by Django 5.2.10 on 2026-03-12 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_word_example_word_example_translation_word_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='vocab.word'),
        ),
    ]
