# Generated by Django 6.0.1 on 2026-01-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.languagelevel'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='vocab_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocab.vocabularylist'),
        ),
    ]
